stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: diegocanas/pi2

before_script:
  - echo "$DOCKER_ID" | docker login -u "diegocanas" --password-stdin
  - apt-get update -qy
  - apt-get install -y docker.io
  - export PATH=$PATH:/usr/bin/docker
  
build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME:latest

deploy:
  stage: deploy
  script:
    - minikube start
    - helm install pi2 helm-chart/
    - sleep 100s
    - kubectl get pods
    - minikube service pi2-helm-chart --url
    - curl $(minikube service pi2-helm-chart --url)
