image: node:latest
stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: diegocanas/pi2

before_script:
  - apt-get update -qy
  - apt-get install -y docker.io
  - export PATH=$PATH:/usr/bin/docker
  - apt-get update -qy
  - apt-get install -y curl
  - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
  - sudo dpkg -i minikube_latest_amd64.deb
  - export PATH=$PATH:/usr/local/bin

test:
  stage: test
  script:
    - echo "Running tests"
    - npm install

docker_build:
  image: docker:24.0.5
  services:
  - docker:24.0.5-dind
  stage: build
  before_script:
    - echo "$DOCKER_ID" | docker login $DOCKER_REGISTRY --username diegocanas --password-stdin  
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME:latest

helm_deploy:
  stage: deploy
  script:
    - minikube start --driver=docker
    - helm install pi2 helm-chart/
    - sleep 100s
    - kubectl get pods
    - minikube service pi2-helm-chart --url
    - curl $(minikube service pi2-helm-chart --url)
