name: CI/CD PI2

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image Docker
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "diegocanas" --password-stdin
        docker build -t diegocanas/pi2 .
        docker push diegocanas/pi2:latest
    
    - name: Start Minikube
      run: 
        minikube start

    - name: Install Helm Chart
      run:
        helm install pi2 helm-chart/

    - name: Wait for Pods to be Ready
      run: 
        sleep 100s

    - name: Check Pod Status
      run: 
        kubectl get pods

    - name: Get IP
      run: |
        minikube service pi2-helm-chart --url
        curl $(minikube service pi2-helm-chart --url)

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        sudo mv ngrok /usr/local/bin/ngrok

    - name: Expose Service with ngrok
      run: |
        export NODE_PORT=$(kubectl get service pi2-helm-chart --output='jsonpath="{.spec.ports[0].nodePort}"')
        ngrok http $NODE_PORT




